server:
  port: 8080

spring:
  profiles:
    active: pro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Ho_Chi_Minh
  mail:
    host: smtp.gmail.com
    port: 587
    username: chihuahua522861@gmail.com
    password: bcxh kugu rdab mohj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB


jwt:
  signerKey: "kaeyazqva8OoomPSUJeGlMKoP09zUqh6caZmiYDSfjxfMoI8WJpbiFxyQFP5PNeh"
  valid-duration: 3600 #second
  refreshable-duration: 3600 #second

